name: i18n-build
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: sh scripts/build.sh
      - name: Install gettext
        run: sudo apt-get install gettext -y
      - name: Compile po files
        run: sh scripts/compile.sh
      - name: Run dist
        run: python3 scripts/dist.py
